README.md
I also added the tidbits I was missing when getting it to work such as dependencies and how to specify another ssh port.
=> Rewrote readme to contain the install and usage information

README.md, terminal/TerminalClient.cpp, terminal/TerminalServer.cpp
Fixed compilation on Debian by changing the way gflags is imported.
(Sorry, I messed up the commits a bit, am not using Git usually.)
=> Fix gflags compilation issue

launcher/et
Tested and works with and without the username
=> AA: Fixing redundant forcing of current user and allowing ssh to pick username based on host

usermanual.md
Partial fix for #48
Signed-off-by: Mriyam Tamuli <mbtamuli@gmail.com>
=> Add usage example for non-standard ssh port

launcher/et
Partial fix for #48 
Signed-off-by: Mriyam Tamuli <mbtamuli@gmail.com>
=> Add example for ssh command in launcher help

terminal/TerminalClient.cpp
Here are some log entries after the change.
./et -t="8000-8003:21-24" server:8080
./et -t="8000-8003:21-24, 8010-8012:9000-9002" server:8080
=> Add port forward range in -t

README.md
I needed to look them up for a couple of machines, this'll save others the trouble :).
=> Improve dependencies information

terminal/SshSetupHandler.cpp, terminal/SshSetupHandler.hpp, terminal/TerminalClient.cpp
* Add -x to kill old sessions of the same user (excluding root)
* For ssh options like jumphost and username, use cmdline > sshconfig > local username(only for USER)
=> Add -x to kill old sessions

src/BackedReader.cpp, src/BackedWriter.cpp, src/ClientConnection.cpp, src/Connection.cpp, src/FakeSocketHandler.cpp, src/ServerConnection.cpp, src/UnixSocketHandler.cpp, terminal/PortForwardHandler.cpp, terminal/SshSetupHandler.cpp, terminal/TerminalClient.cpp, terminal/TerminalServer.cpp, terminal/UserTerminalHandler.cpp, terminal/UserTerminalRouter.cpp
Easylogging entries provide a new line at the end. Removing extra lines.
=> remove extra lines in log file

terminal/SshSetupHandler.cpp
This PR should fix issue #109.  I only tested the scenario without -J (temporary limited resources) and it works. Will update when I have more resources to test -J.
=> start etserver in interactive mode

terminal/SshSetupHandler.cpp
Reverts MisterTea/EternalTerminal#110
=> Revert "start etserver in interactive mode"

terminal/SshSetupHandler.cpp
Reverts MisterTea/EternalTerminal#111
=> Revert "Revert "start etserver in interactive mode""

src/terminal/TerminalClient.cpp, src/terminal/TerminalServer.cpp
While debugging #120, enabling these vlogs might help us understand what's going on inside et & network
=> Enable a few vlogs to help debugging

README.md
Update the documentation in README.md using the documentation in gh-pages to make it clear that a debian repo exist for github users.
Update the "install from source" for debian.
=> Update README.md with debian instruction for installation

src/terminal/SshSetupHandler.cpp
fixed #128 
Try to give more suggestions to fix when ET connect fails.
=> better error msg in ET connect

src/base/BackedReader.cpp, src/base/BackedReader.hpp, src/base/BackedWriter.cpp, src/base/BackedWriter.hpp, src/base/ClientConnection.cpp, src/base/Connection.cpp, src/base/Connection.hpp, src/base/FlakySocketHandler.hpp, src/base/Headers.hpp, src/base/PipeSocketHandler.cpp, src/base/RawSocketUtils.cpp, src/base/ServerConnection.cpp, src/base/ServerConnection.hpp, src/base/SocketHandler.cpp, src/base/UnixSocketHandler.cpp, src/terminal/TerminalServer.cpp, test/BackedTest.cpp, test/ConnectionTest.cpp, test/FlakySocketHandler.hpp
Sadly this didn't expose any bug in ET to fix, but the unit tests are passing now.
=> Fix unit tests

README.md
as suggested i modified the readme to include the instruction for building for Debian/Ubuntu (systemd service and config file).
=> build from source debian

src/base/DaemonCreator.cpp, src/base/DaemonCreator.hpp, src/base/Headers.hpp, src/htm/HtmClientMain.cpp, src/terminal/SshSetupHandler.cpp, src/terminal/Terminal.cpp, src/terminal/TerminalClient.cpp, src/terminal/TerminalServer.cpp
=> Handle login prints.

README.md
Created installation instructions for CentOS 7
=> CentOS7 install docs

src/base/SocketEndpoint.hpp, src/base/SocketHandler.hpp, src/base/base64.hpp, src/base/sole.hpp
Hi again,
This is just a pull request that fixes some minor warnings when linking the static libraries through Xcode. It's not majorly important.
=> Small warning fixes

README.md
Per https://github.com/MisterTea/EternalTerminal/issues/211#issuecomment-519198645
=> Replace wget/unzip with git --recurse-submodules

src/terminal/PsuedoUserTerminal.hpp
... just before exec'ing $SHELL, so child processes of the shell receive
SIGCHLD, even if the shell is not smart enough to do this itself (bash,
e.g.).
=> reset SIGCHLD to SIG_DFL

rc.d/etserver
See issue #253
Tested with Eternal Terminal v6.0.4 on FreeBSD 12.1-RELEASE-p1.
=> FreeBSD: Create rc.d service file

index.html
Corrects small spelling error:
funtionality -> functionality
=> Correct spelling error.

src/terminal/TerminalServerMain.cpp
=> Fix port flag on etserver

docker/Dockerfile.client, docker/Dockerfile.server, docker/README.md, docker/container-entrypoint
Hi there. I need some help figuring this out.
This is an initial docker image build for et-server, but there is something missing here.
Build it with: `cd docker && make `
Run it with: `docker run -it --rm -p 2022:2022 et-server`
The issue is this:
```
$ docker run -it --rm -p 2022:2022 et-server
+ '[' server == server ']'
+ shift
+ exec etserver --logtostdout -v 1 --cfgfile=/etc/et.cfg
[INFO 2020-02-22 21:33:43,380 etserver-main TerminalServerMain.cpp:143] In child, about to start server.
[INFO 2020-02-22 21:33:43,381 etserver-main TcpSocketHandler.cpp:202] Listening on 0.0.0.0:2022/2/1/6
[INFO 2020-02-22 21:33:43,382 etserver-main TcpSocketHandler.cpp:202] Listening on 0.0.0.0:2022/10/1/6
[INFO 2020-02-22 21:33:43,382 etserver-main TerminalServer.cpp:20] Creating server
[V1 2020-02-22 …
```
=> Docker container image [need help]

README.md
It doesn't really change anything, just less characters to type. lol
=> README: Use "now" option instead of start command

README.md
to keep the main sources file clean and tidy.
=> Put et source into a seperate file

.github/workflows/linux_ci.yml, src/base/TcpSocketHandler.cpp, src/terminal/UserJumphostHandler.cpp, src/terminal/forwarding/ForwardSourceHandler.cpp
Minimize amount sent to Sentry.  #382
=> Move some error logs to warnings

src/terminal/ParseConfigFile.hpp
Backported libssh commit 1ba6ef689fe7f702d9921271dd422cae885de788
I'm having quite big `.ssh/config` and a very mysterious issue like this.
Note, hosts are different, should not match, x.x.x.x is _not in the config at all_
```
./et --logtostdout x.x.x.x
Parsed ssh config file, connecting to y.y.y.y
```
On my x64-osx(11.2.2) it happens at least in 10% with a single-host config (not sure what's special in it) and 100% in my working config with >50 hosts, but clear reproduce steps are hard. However, on my laptop this is reproducible with both clang-12.0.0 and gcc-10.2.0
From my understanding it happens like this:
- this [SOC_HOST parsing for loop](https://github.com/MisterTea/EternalTerminal/blob/b11784967704dcd86bbbe2fb930595f0c9404cf8/src/terminal/ParseConfigFile.hpp#L1227L1228) consumes …
=> Fix occasional Host missmatches

etc/et.cfg, src/terminal/TelemetryService.cpp
For MisterTea/EternalTerminal#504
=> Sentry shutdown message fix and telemetry config option example

src/base/TunnelUtils.hpp
=> Fix cross build with GCC 12

.circleci/config.yml, .github/workflows/novcpkg_build.yml, .github/workflows/vcpkg_build.yml, CMakeLists.txt, src/base/Headers.hpp, test/TestHeaders.hpp, vcpkg.json
This homogenizes the deps between vcpkg and submodules to allow building from either.
=> Move deps to vcpkg pt 2

src/base/Headers.hpp, test/ServerFifoPathTest.cpp
=> Fix experimental filesystem header

README.md
=> updated install instructions for debian
