- launcher/et
`LC_ALL`, if set, overrides `LC_CTYPE`. This causes `tr: Illegal byte sequence` error in some systems.
> et: change LC_CTYPE=C to LC_ALL=C

- launcher/et
This allows et to connect to execute the password command on servers that do not have a BASH compatible shell as the default.
I don't feel like this is the *best* approach to this problem. However, it does work for me.  With a remote shell of `/usr/local/bin/fish`, the password command now succeeds.
It's possible that this will cause problems with the `--ssh=` parameter if the user adds a command rather than just flags.
> Change SSH command to invoke '/bin/bash' on connection

- terminal/ParseConfigFile.hpp
- terminal/TerminalClient.cpp
Support parsing ssh config files for et to use. User-specific config file(~/.ssh/config) has higher priority than system-wide config file(/etc/ssh/ssh_config). 
Currently these options below are parsed. Hostname field is used to help translate et host field. 
For example, if you have a hostname alias `dev` for `someremotemachine.com`. you can now do `et dev:8080` instead of `et someremotemachine.com:8080`.
Support for other config options can be added based on request(such as jumphost).
```
Include (to include another config file)
Host
Hostname
port
username
connecttimeout
protocol
stricthostkeychecking
userknownhostsfile
proxycommand
GSSAPISeverIdentity
GSSAPIClientIdentity
GSSAPIDelegateCredentials
```
> SSH config file parser

- CMakeLists.txt
- terminal/TerminalServer.cpp
The changes are really simple:
1. Don't need SELinux on FreeBSD (for obvious reasons), and compilation fails for some reason if find_package is called looking for it. So I added a guard around that.
2. FreeBSD doesn't need, and in fact can't use libresolv, with that functionality in libc. This meant two changes, one of which can **definitely** be done better. The first is to include sys/socket.h in the FreeBSD includes block. The second is to not link in libresolv. My experience which cmake is very limited, but this seemed to work for me.
Clearly the linking changes in `CMakeLists.txt` could be better, so whatever needs to be done for that just let me know.
Lastly, creating a port for this, so et can be available as a package in the standard set on FreeBSD, should be relatively …
> Make compliation on FreeBSD work

- README.md
- terminal/ParseConfigFile.hpp
- terminal/SshSetupHandler.cpp
- terminal/TerminalClient.cpp
1. Fix missing newline in reading config file, which randomly cause corrupted hostname
2. Update -h info, rename flag user to u for short.
3. Update README back to the usage similar to ssh.
4. run format.sh
> Fix missing line in reading config file; Update Readme; format.sh

- src/Connection.cpp
- terminal/TerminalServer.cpp
* Explicitly use Connection::closeSocket() to differentiate with the one in ClientConnection (which also contains reconnect)
* If jump client is idle, kill the jump->dst connection and restore when the src is back.
* Added some log to LOG(ERROR) due to the current log library issue.
> Fix jump connection

- etc/et.cfg
- proto/ETerminal.proto
- terminal/TerminalServer.cpp
- terminal/UserTerminalHandler.cpp
- terminal/UserTerminalRouter.cpp
1. Before this PR all terminal specific logs are aggregated by user, stored in /tmp/etserver.{hostname}.{username}.log.INFO.{time}. We cannot tell the difference between log entries from different terminals of the same user. After the change, these logs are created per terminal session, named as /tmp/etserver_terminal_{ID}.INFO.{time}. This way it's much easier for debugging.
2. Add verbose level in /etc/et.cfg. 
Note that only et daemon started by systemd uses /etc/et.cfg, which means a new terminal/jumphost session will be created without reading this file and their VLOG level are not affected. We can definitely make them also read this section, although sounds a bit tricky. What do you think? @MisterTea
> Fix log issues

- src/Headers.hpp
- terminal/ParseConfigFile.hpp
Sometime before the last release compilation on FreeBSD was broken. The fix is related to calls to getline. A few options for macros to fix exist according to `man getline` on a FreeBSD-11.1-STABLE machine
- define  `_POSIX_C_SOURCE` to be 200809 or greater
- define `_WITH_GETLINE`, which is the option I chose
- define `_BSD_SOURCE`
- define `_GNU_SOURCE`
The previously mentioned manpage lists the reason as compatibility. It further calls out the last two of those options as GNUisms. `_WITH_GETLINE` seemed like the most descriptive, and less likely to break elsewhere versus `POSIX_C_SOURCE`
FWIW, I'd still like to get ET added to the FreeBSD ports but a release that builds will make that easier so patches don't have to be kept and so on.
[Edited for extra ` placement]
> Add FreeBSD #define to turn on getline in stdlib

- src/Headers.hpp
- src/UnixSocketHandler.cpp
- terminal/TerminalClient.cpp
- terminal/TerminalServer.cpp
- terminal/UserTerminalHandler.cpp
- terminal/UserTerminalRouter.cpp
This adds the necessary `#include`s and `#if`s for getting et up and going on NetBSD.
- NetBSD doesn't have all of the `ai_flags`
- Uses `freopen` and passes `stderr` as an arg, rather than assigning to it.
- Calls `waitpid` instead of `waitid`. NetBSD-7 doesn't have `waitid`. The manpage for NetBSD-CURRENT has `waitid` so presumably the OS specific bit can be removed once NetBSD-8 is released.
- This also removed some `#include`s that were in a conditional branch, but also unconditionally brought it.
In particular, I imagine the way `freopen` is handled is suboptimal. My underdeveloped C++ skillset is showing sadly. But this got everything to work. Any suggestions on improvement are appreciated.
> Compliation on NetBSD

- terminal/RawSocketUtils.cpp
- terminal/RawSocketUtils.hpp
- terminal/TerminalClient.cpp
- terminal/TerminalServer.cpp
- terminal/UserTerminalHandler.cpp
- terminal/UserTerminalRouter.cpp
* throw runtime error in raw socket read/write
* remove LOG(FATAL) for calls to raw socket read/write
* catch runtime error from raw socket read/write and LOG(FATAL) them except for runJumphost and runTerminal.
* close(routerFd) when jump client exit normally
* format code
> Throw error in raw socket read/write

- sandbox/TestBacked.cpp
- sandbox/TestConnection.cpp
- sandbox/TestFakeSocketHandler.cpp
- sandbox/TestFlakyConnection.cpp
- terminal/LogHandler.cpp
- terminal/LogHandler.hpp
- terminal/TerminalClient.cpp
- terminal/TerminalServer.cpp
Previously we had to set log filename even when logging is off. Otherwise it causes a hang. This is fixed by setting MaxLogFileSize after the log filename is set.
> Fix hang when filename is not set

- terminal/TerminalClient.cpp
- terminal/TerminalServer.cpp
etserver didn't show version correctly on Ubuntu. Move the setVersionString() before GFLAGS parsing arguments fixes the problem.
> move setVersion up

- terminal/ParseConfigFile.hpp
- terminal/TerminalClient.cpp
* Remove LOG(FATAL) when read() returns 0 from stdin. As in some emulators it's valid. https://stackoverflow.com/questions/8975521/read-from-stdin/8975733#8975733
* Removed an extra line
> read() return 0 from stdin is valid

- terminal/SshSetupHandler.cpp
Accoording to http://man7.org/linux/man-pages/man3/exec.3.html, execl() requires full path to the binary while exelp() can search in PATH. So replacing this for ssh so that #102 can be resolved.
> use ssh in PATH instead of hardcoded

- etc/et.cfg
- terminal/LogHandler.cpp
- terminal/LogHandler.hpp
- terminal/TerminalClient.cpp
- terminal/TerminalServer.cpp
- Enable log rotation in easylogging.
- Set the max log file to 20MB, log file will be deleted when exceeding size limit.
> setup easylogging log rotation-20M

- terminal/TerminalServer.cpp
Originally I thought it makes more sense to keep the connection alive only if there's something from client to server direction. However, it's possible that writing from server to client(on jumphost that's from dst terminal to local router) takes too long and use up all the keepalivetime(7s) since last sync with client, which finally result in a fake disconnection from jumphost's perspective. Referring to https://github.com/MisterTea/EternalTerminal/blob/master/terminal/TerminalClient.cpp#L440, we also increase keepaliveTime when something is sent from server to client direction, which turns out to make the jumphost connection more stable in the experiments. 
Also add some VLOG messages for debugging purpose.
> Increase keepaliveTime when get message from dst terminal to router

- CMakeLists.txt
Just a tiny fix to get things compiling again on FreeBSD.
As soon as a new version is released I'll update the FreeBSD package.
Also, I've setup some smoke-test CI for each of FreeBSD, NetBSD, and OpenBSD. These weren't running the tests, but seeing the CircleCI setup, I'll be switching to that soon. If there is interest I can expose the status of these, or the logs. It's a pretty simple buildbot setup so far, but whatever would be helpful I can make accessible.
> Link with execinfo on FreeBSD because easylogging needs it

- CMakeLists.txt
- proto/ET.proto
- proto/ETerminal.proto
- src/base/Headers.hpp
- src/base/SocketHandler.hpp
- src/terminal/TerminalClient.cpp
Hi,
This pull requests switches from using the full protobuf library to the lite version, which reduces our binary size by about 10 MB.
The `DebugString()` method was the only full protobuf feature being used in the ET code. It was being used in a few logs. I was able to provide a suitable replacement for the log line in which we know the message type, but the other two log lines are in templated methods. The best I could do there was to replace the debug string with the message type.
If this will make diagnosing issues too difficult, I could look into perhaps `#ifdef` ing the code into lite and regular variants.
Thanks!
> Switch to using the protobuf-lite library

- README.md
- src/base/DaemonCreator.cpp
- src/base/DaemonCreator.hpp
- src/htm/HtmClientMain.cpp
- src/terminal/TerminalMain.cpp
- src/terminal/TerminalServerMain.cpp
- systemctl/et.service
DaemonCreator forks twice which confuses systemd, so this changes has
the main child process write a pidfile which can be referenced in the
et.service systemd configuration.
> Write a pidfile for the 2nd child process for systemd.

- src/terminal/TerminalClientMain.cpp
- src/terminal/TerminalMain.cpp
- src/terminal/TerminalServerMain.cpp
While I was debuging an issue, I didn't realize the verbose flag
required an arg (I was thinking ssh like -v or -vvv).  This change
handles option parsing exceptions and displays the issue and then the
help menu. I also added a short flag for help (-h) to
etserver/et/etterminal.
> Add exception handling to cxxopt usage.

- src/base/LogHandler.cpp
Hi again,
This is a change that allows libet to be compiled on iOS. The only change is that instead of calling `system()` to remove a file using `rm`, it uses the C++ standard `remove()` function.
I am unaware of any platform that EternalTerminal supports that has `rm` but not `remove()`, but I am more than happy to make changes if this causes a compatibility problem.
> iOS: Use remove() instead of system() to remove log files

- src/base/Connection.cpp
- src/base/UnixSocketHandler.cpp
Hi,
These are a couple small changes which prevent calling `FATAL_FAIL` when iOS terminates the connection of an app that's suspended in the background.
The `isSkippableError()` function is called when reading or writing to/from a connection. If the error is skippable, the code assumes the connection has failed and calls `closeSocketAndMaybeReconnect()`. It seems safe to me to add `ENOTCONN` to the list of skippable errors in this context.
The other change prevents calling `close()` on an invalid file descriptor.
> Fix fatal log errors caused when iOS closes background connections

- src/terminal/ParseConfigFile.hpp
Adds support for tilde in included config files (which is supported by ssh).  Example:
```
Include ~/.ssh/conf/settings.ssh
Include ~/.ssh/conf/hosts.ssh
```
Related to https://github.com/MisterTea/EternalTerminal/issues/197
Severely lacking any cpp skills so let me know if I should change something.
> Expand tilde before parsing include file

- CMakeLists.txt
- build_static.sh
Hi again. It's been a while.
We recently found that easylogging's default crash log installs a signal handler that interferes with our own signal handler when linking `libet`. Thankfully, it's fairly easy to disable, so I figured I would offer an upstream pull request for a build option to disable it.
Thanks for considering it!
> Add a build option to disable easylogging's default crash handler

- CMakeLists.txt
The `target_link_libraries` list for `et-test` included `util` and `resolv` in the list, but these are already in `${CORE_LIBRARIES}` when needed, which itself is in that list already.
This prevented building Eternal Terminal v6.0.4 from source on FreeBSD, since for FreeBSD, libresolv is not a thing and instead the relevant functions are part of the FreeBSD standard C library like you know (since you were already handling that for `${CORE_LIBRARIES}`).
> Remove duplicate/incorrect entries from target_link_libraries for et-test in CMakeLists.txt

- README.md
Without libprotobuf-dev installed, on Ubuntu I got `error while loading shared libraries: libprotobuf-lite.so.10: cannot open shared object file: No such file or directory`. After installing it, `et` started fine.
> Mention that libprotobuf-dev is also required (by the client)

- src/terminal/ParseConfigFile.hpp
- src/terminal/TerminalClient.cpp
- src/terminal/TerminalClient.hpp
- src/terminal/TerminalClientMain.cpp
- test/JumphostTest.cpp
- test/TerminalTest.cpp
Adds a CLI flag to specify the SSH agent socket to forward. Although the
socket held in `SSH_AUTH_SOCK` is the default, multiple agents may run
and this allows forwarding a specific agent.
Both SSH agent forwarding and a specific SSH agent socket to use may be
specified in `ssh_config` or `~/.ssh/config`, using the `ForwardAgent`
and `IdentityAgent` parameters. EternalTerminal now knows how to parse
those options and will use them to forward an SSH agent socket and
choose the correct socket based on the values set in the config file i
CLI flags are not given.
Verified by connecting to ET using no CLI flags, only
`--forward-ssh-agent`, only `--ssh-socket`, and both CLI flags. Sockets
were correctly forwarded, with `--ssh-socket` taking priority over a
value set in `ssh_config`.
> Add CLI flag for SSH socket to forward and config file parsing

- src/terminal/ParseConfigFile.hpp
Currently 'Match host' is ignored in SSH options parsing, this can lead
to the situation where if the next line is (for example) 'User foo',
that this option gets applied globally.
Fix this by treating any line that has the form of 'Match <tokens>' as
'[tokens]'. This way 'Match host <options>' gets treated as 'host [options]'.
> support 'Match host' in SSH config files

- README.md
`github.io` doesn't seem to properly serve files stored in Github LFS. It only serves LFS metadata, not the whole file.
Also Debian stretch source doesn't work with Debian buster, which is the most recent stable release.
Resolves: https://github.com/MisterTea/EternalTerminal/issues/245
> Update Debian installation instruction

- src/terminal/TerminalClient.cpp
- src/terminal/forwarding/PortForwardHandler.cpp
As of 1b3a488, forwarding named sockets is supported in the core, but
the only socket accessible to forward was the SSH auth socket.
This is resolved by allowing arbitrary named sockets alongside numeric
port forwards with `-t`/`-r`.
Fixes #292.
--
I am unsure of the changes to `PortForwardHandler.cpp`, so I left it commented instead of removing. Everything _seems_ to work and test fine. I'm very much unfamiliar with C++, apologies if there's something egregiously wrong here.
> Parse named socket port forwards (Fixes #292)

- src/terminal/TerminalClient.cpp
#293 accidentally introduced a bug where the `reverseTunnels` ctor parameter to `TerminalClient` was parsed to get both the forward and reverse tunnels. This change fixes the typo and uses `tunnels` for forward tunnels, as intended.
> fix input for forward tunnels

- README.md
Follow redirects with curl using `-L` option while adding debian gpg key.
without `-L`  gpg errors out "no valid OpenPGP data found"
with `-L` installation works!
> Fix debian installation instructions

- download.md
The current distribution name is buster and no longer stretch.
Also the path for the source file changed to not change the system one but create a new file just for et which keeps the system tidy.
> Update Debian install instructions

- deployment/debian/debian_SOURCE/et.service
- systemctl/et.service
This fixes the following warning:
```
PIDFile= references a path below legacy directory /var/run/, updating /var/run/etserver.pid → /run/etserver.pi
```
> Fix warning by systemctl

- README.md
The sed script in CentOS 7 building guide has an error, which causes the `--daemon` argument deleted in systemd configuration file, and makes `systemctl start et.service` failed.
`.*` in the original sed script is ambigious, which would match all characters including space, so that only the last argument will be reserved.
`[^[:space:]]*` in the new sed script is identical to the better known `[\S]*` due to the sed's incompatibility with PCRE.
before:
```
ExecStart=/wrong/path --daemon --cfgfile=/etc/et.cfg
```
after: 
```
ExecStart=/right/path --cfgfile=/etc/et.cfg
```
the `--daemon` is lost.
before:
```
ExecStart=/wrong/path --daemon --cfgfile=/etc/et.cfg
```
after: 
```
ExecStart=/right/path --daemon --cfgfile=/etc/et.cfg
```
the `--daemon` will be reserved.
> Fix sed error in CentOS 7 building guide

- deployment/debian/debian_SOURCE/et.service
- systemctl/et.service
Using `Type=forking` is discouraged, since systemd works best when the processes are just running in foreground.
Change to `Type=simple` and drop the `--daemon` argument.
We don't need a `PIDFile=` in this service unit either.
Also stopped seeing this message on the journal, upon restart of the service (not sure exactly why this was happening):
```
systemd[1]: et.service: Supervising process 12345 which is not our child. We'll most likely not notice when it exits.
```
Tested by making these changes to a host and ensuring I was still able to connect to the et server.
> Run EternalTerminal server as a Type=simple systemd service

- CMakeLists.txt
- src/base/Headers.hpp
- src/base/TcpSocketHandler.cpp
- src/htm/HtmClientMain.cpp
- src/htm/HtmServer.cpp
- src/htm/HtmServerMain.cpp
- src/terminal/ParseConfigFile.hpp
- src/terminal/TerminalMain.cpp
- src/terminal/TerminalServerMain.cpp
- src/terminal/UserTerminalRouter.hpp
- src/terminal/forwarding/PortForwardHandler.cpp
- test/BackedTest.cpp
- test/ConnectionTest.cpp
- test/FakeConsole.hpp
- test/JumphostTest.cpp
- test/Main.cpp
- test/TerminalTest.cpp
Works both completely locally in Termux without root, and when connecting to a linux server. Only remaining issue is that `etserver --help` doesn't work: I think that's because `cxxopts` is incompatible with LLVM libc++, as this patch runs fine on linux x86_64 with GNU libstdc++. I will look into that and patch that last bug later.
> Add Android support

- systemctl/et.service
With Restart=on-failure, the service will be restarted when the process
exits with a non-zero exit code, is terminated by a signal, when an
operation (such as service reload) times out, and when the configured
watchdog timeout is triggered.
Setting this to on-failure is the recommended choice for long-running
services, in order to increase reliability by attempting automatic
recovery from errors.
> Run EternalTerminal systemd service with Restart=on-failure

- src/terminal/SshSetupHandler.cpp
- src/terminal/SshSetupHandler.hpp
- src/terminal/TerminalClientMain.cpp
We'd like to be able to pass arbitrary ssh `-o` config options
down to the underlying ssh command.
Following the suggestions in the last comment on:
https://github.com/MisterTea/EternalTerminal/issues/72
this commit adds a vector of string arguments that can be passed down.
As part of this, tidy up construction of the ssh args list to remove
some redundant string -> c_string -> string conversion and clarify the
control flow a bit.
Test Plan:
I tried running this, with an option picked at random to have
no real effect other than showing up in the argument list:
```
$ ./et --ssh-option RequestTTY=yes SOME.HOST
```
then inspecting the process listing I can see that it made it
into the ssh command that gets run:
```
ssh USER@SHOME.HOST -oRequestTTY=yes echo 'XXXXXXX_xterm-256color\012' | …
```
> Add --ssh-option argument for passing arguments to ssh

- CMakeLists.txt
E.g. the static library may not exist or may not be the one to use.
> Do not hard code protobuf lookup properties when using external protobuf

- CMakeLists.txt
We might want to build ET without Sentry in unforeseen circumstances
(e.g. on Fedora and EL, Sentry does not compile on ppc64le and s390x).
Add DISABLE_SENTRY that works the same way as DISABLE_VCPKG - if set,
ET is built without Sentry support.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mistertea/eternalterminal/414)
> Allow disabling Sentry

- src/htm/TerminalHandler.cpp
- src/terminal/PsuedoUserTerminal.hpp
I use dash as my login shell and noticed that etterminal launches SHELL with --login, which dash doesn't support.
Since -l seems to be supported by the major shells like bash and zsh, I'm wondering whether this could be an appropriate change to support dash as well.
Thanks!
> Execute shell with -l rather than --login for dash compatibility

- README.md
Added `ninja-build` and `zip` to Ubuntu/Debian dependencies.
Merged the two Ubuntu/Debian build-from-source instructions into one (under the Build from Source section).
Added conditional `VCPKG_FORCE_SYSTEM_BINARIES=1` so ARM builds work on MacOS and Ubuntu/Debian.
Added instructions to persistently run an `et` server daemon on MacOS.
Feel free to edit/suggest changes.
> Add Missing Deps, How to Run Daemon on Mac, Cleanup

- src/base/Headers.hpp
- src/terminal/TerminalClient.cpp
- src/terminal/TerminalClient.hpp
- src/terminal/TerminalClientMain.cpp
- test/JumphostTest.cpp
- test/TerminalTest.cpp
hello! thanks for a great tool. this PR (should) make the client keep-alive duration configurable.
i created this because i noticed that reconnection times seemed to be slow sometimes (especially when compared to mosh) and am suffering frequently from lost keys. i realize that UDP is probably better suited for cases where there is frequent switching but many public wifi networks (at least in my locale) has some sort of filtering in place that makes EternalTerminal much more practical to use.
disclaimer: i don't have any actual data that this would improve the situation for my use case, because i'm still having issues building on MacOS M1. but this seemed like a fast enough change that i thought i'd make it and get some feedback :)
please take a look, thanks!
> add configurable client keep-alive duration

- deployment/debian/debian_SOURCE/control
The debian build system will add all the necessary dependencies
automatically, so -dev dependencies are only needed in Build-Depends.
> drop -dev dependencies on debian

- .circleci/config.yml
- .github/workflows/vcpkg_build.yml
For vcpkg CI, add libraries such as libsodium, based on the list used in the Ubuntu devcontainer and README.md. This should fix vcpkg CI failures I see in my fork. I'm not sure why it doesn't fail in the main repo, however.
For circle CI, ignore error if the `~/.ssh/authorized_keys` file does not exist when trying to delete it, by switching to `rm -f`
This should fix the errors from #510 and #511.
> Circle CI and Linux GitHub Action vcpkg CI fixes

- src/base/Headers.hpp
- src/base/UnixSocketHandler.cpp
- src/terminal/TerminalServer.cpp
With etserver v6.1.9, attempts to reconnect cause the etserver process
to crash due to an unexpected EGAIN in UnixSocketHandler::close.
Suppressing this by ignoring EAGAIN allows etserver to keep running
but the reconnect still fails since the call to close causes the
select in TerminalServer::runTerminal to complete with EBADF and
an attempt to read from terminalFd which returns EAGAIN (since it
is non-blocking) and the terminal server session ends.
Handling EGAIN in both places allows the reconnect to succeed and
re-join the terminal server session reliably.
> Fix reconnects on FreeBSD

- .clang-format
- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .devcontainer/reinstall-cmake.sh
This PR has two changes:
* Add a devcontainer, which sets up an environment that is sufficient to build with both gcc/clang.  This can be launched in docker or in GitHub Codespaces, for example.  I chose ubuntu-21.04 since it supports running on M1.
* Add a `.clang-format` file so that using format-on-save works and can automatically detect the style.
For the devcontainer, it is mostly unmodified from the automatically-generated boilerplate.  The following small changes were made:
* Switched to a newer version of cmake (specifically `ARG REINSTALL_CMAKE_VERSION_FROM_SOURCE="3.23.1"`)
* Installed the dependency packages based on `README.md`, with some small update to use `libcurl4-openssl-dev` (this is noted with a comment).
* Run `git submodule update --init --recursive` after launching …
> Create devcontainer and add .clang-format to simplify development

- CMakeLists.txt
- src/terminal/TerminalServer.cpp
- src/terminal/UserTerminalRouter.cpp
- test/FuzzableTerminalServer.hpp
- test/TerminalServerFuzzer.cpp
- test/TerminalServerRouterFuzzer.cpp
etserver has two interfaces, the "server" and "router". Add fuzzers for
each of these, and fix crashes from invalid input to the router
(internal) interface.
The fuzz build currently requires libFuzzer and clang, and can be
invoked with:
```
export CC=/usr/bin/clang
export CXX=/usr/bin/clang++
mkdir build && cd build
cmake -DSANITIZE_ADDRESS=ON -DFUZZING=ON ../
make -j`nproc`
```
To run the fuzzers:
```
mkdir router-corpus
cd router-corpus
../TerminalServerRouterFuzzer -jobs=10 .
mkdir server-corpus
cd server-corpus
../TerminalServerFuzzer -jobs=10 .
```
These will keep running unless they hit a crash.
Note that easyloggingpp still overrides the signal handlers, so doing a
Ctrl-C will trigger a spurious crash report, but these can be safely
ignored.
The integration can still be improved, …
> Add simple fuzzers for etserver sockets

- CMakeLists.txt
- src/base/ServerClientConnection.cpp
- src/base/ServerClientConnection.hpp
- src/base/ServerConnection.cpp
- src/base/ServerConnection.hpp
- src/terminal/ServerFifoPath.cpp
- src/terminal/ServerFifoPath.hpp
- src/terminal/TerminalMain.cpp
- src/terminal/TerminalServer.cpp
- src/terminal/TerminalServerMain.cpp
- src/terminal/UserJumphostHandler.cpp
- src/terminal/UserJumphostHandler.hpp
- src/terminal/UserTerminalHandler.cpp
- src/terminal/UserTerminalHandler.hpp
- src/terminal/UserTerminalRouter.cpp
- src/terminal/UserTerminalRouter.hpp
- test/ServerFifoPathTest.cpp
- test/TerminalTest.cpp
Add additional verification when connecting terminals to etserver:
* Reject more than one terminal connecting per launch.
* Ensure that the launched terminal's passkey matches on connect.
* Fix race condition if more than one terminal launches.
To protect the router fifo path, move it to either /var/run, $XDG_RUNTIME_DIR (with a fallback to $HOME/.local/share), depending on if the etserver process is running as root.
If the $HOME/.local/share directory does not exist, it will be created. Note that as a side effect of this change, if etserver is running as a non-root user it may only be connected by the same user, since it now places the fifo in the user-specific $XDG_RUNTIME_DIR or $HOME directory.
For connecting to the pipe, update etterminal to probe to detect the pipe to use, first …
> Add additional checks to connection path and relocate router fifo

- src/base/Headers.hpp
- src/terminal/TelemetryService.cpp
- src/terminal/TerminalMain.cpp
- src/terminal/TerminalServer.cpp
This fixes #503, where etserver crashed if select returned an EINTR error code. This is apparently normal behavior, and the caller is expected to retry when this occurs.
For codepaths that `FATAL_FAIL` on the select results, add special handling to retry instead of crashing. Note that the specific approach varies for each callsite.
Doing this impacts SIGINT, however, so to keep Ctrl-C working to exit the process fix, update the Sentry SIGINT handler so that it calls `et::InterruptSignalHandler`, enabling the process to exit semi-gracefully (however it still prints a callstack).
To test, first call `etterminal` and do not provide any input:
```
$ ./etterminal
Call etterminal with --idpasskey or --idpasskeyfile, or feed this information on stdin
```
Then launch `etserver` and verify it …
> Handle EINTR exit codes from `select`

- src/base/Headers.hpp
My guess is that the else part is what we will want to return if no
other case catches.
In any case we need a return value to prevent:
`error: control reaches end of non-void function [-Werror=return-type]`
> Always return a value from waitOnSocketData()

- README.md
Adjusting the docs regarding port forwarding as
`user@machine:~$ et -t "2222:2222" remote`
works, while original readme's instructions fail with
```
user@machine:~$ et -t="2222:2222" remote
Exception: Argument ‘-t=2222:2222’ starts with a - but has incorrect syntax
```
Tested with et version 6.2.1
> fix readme regarding port forwarding

- src/base/ServerConnection.cpp
- test/ServerFifoPathTest.cpp
Fix failures likely from CI environment and timing changes
Fix a double-socket-close in ServerConnection, which triggers an STFATAL in UnixSocketHandler, which was showing up on the flaky socket tests.  To fix, if `destroyPartialConnection` is called don't call `close`, since `destroyPartialConnection` already closes the socket.
Unset XDG_RUNTIME_DIR before running tests, since it changes the test behavior, and this appears to now be set by the CI system.
Disable ServerFifoPath tests when run as root, since the creation behavior it is testing is disabled as root, and it leads to a REQUIRE failure.
> Fix test failures that started appearing in CI

- scripts/ssh-et
- Fixes SSH config not being applied to original remote
- Adds retries in case multiple processes are spawned
concurrently (can happen with tmux-xpanes for example)
> ssh-et: apply upstream updates

- README.md
`apt-key` has been deprecated since Debian 11 and will be removed in 12. Writing the GPG key to `/etc/apt/trusted.gpg.d` gets rid of this problem and works entirely the same as `apt-key add`.
> docs: write gpg key to `trusted.gpg.d` for APT

- .circleci/config.yml
- src/base/SubprocessToString.cpp
- src/terminal/PsuedoUserTerminal.hpp
- src/terminal/SshSetupHandler.cpp
- src/terminal/SshSetupHandler.hpp
- src/terminal/TerminalClientMain.cpp
- src/terminal/TerminalMain.cpp
Currently et does not support passing an ipv6 address as the host positional argument is assumed to be an ipv4 address or hostname with a single colon with the port after it and the rest is ignored, eg:
```
$ et 2620:10d:c083:1418:14ac:6bbc:4737:56ee                                                                                                                                     15:19:52  10.07.22  100% █
Could not reach the ET server: 2620:10
```
This change will support ipv4 address or hostname with port specified or ipv6 address with or without port specified.  Currently, if a port is specified in the positional arg, it overwrites what was specified (explicitly or by default) with the -p,--port option. I think this is backwards and may offer a PR to invert this logic.
> Support for ipv6 addresses (with or without port specified)

- .circleci/config.yml
- src/terminal/TerminalClientMain.cpp
This will support ipv6 addresses that are abbreviated with `::` such as
`::1` (for `0:0:0:0:0:0:0:1`) with some caveats around specifying the port
in the host positional argument.
Help output:
```
$> ./et --help
Remote shell for the busy and impatient
Usage:
et [OPTION...] [user@]host[:port]
Note that 'host' can be a hostname or ipv4 address with or without a port
or an ipv6 address. If the ipv6 address is abbreviated with :: then it must
be specfied without a port (use -p,--port).
-h, --help                 Print help
--version              Print version
-u, --username             Username
--host arg             Remote host name
...
```
Tests:
```
$> ./et ::1 -p 8080 --macserver
$> ./et 0:0:0:0:0:0:0:1 -p 8080 --macserver
$> ./et 0:0:0:0:0:0:0:1:8080 --macserver
$> ./et ::1 -p 8080 …
```
> ipv6 abbreviated address support

- init/launchd/homebrew.mxcl.et.plist
For launchd to properly manage the process you do *not* want to daemonize and bg the process otherwise launchd 'loses' the process.
After loading the plist, `sudo launchd list` now shows the et server service with the correct pid and unloading the server kills the process(es).
> Fix launchd plist config to remove daemonization.

- src/terminal/TerminalClientMain.cpp
- src/terminal/TerminalMain.cpp
- src/terminal/TerminalServerMain.cpp
While investigating #541, I ran `et` with `--verbose=9` but realized that the logs created by `et` and `etterminal` were not verbose.  It turns out that the default argv parsing that easyloggingpp does via START_EASYLOGGINGPP(argc, argv) does not mesh well with the cxxopts style options so instead of relying on the default handling of argv/argc in ELPP, let's just explicitly set the verbose level from the cxxopts option argument.  Note that a value greater than 9 defaults to 9 in ELPP so no handling in et/etterminal/etserver is required.
Examples of the discrepancies:
* `et --verbose=5` (cxxopts 5, ELPP 0) 
* ELPP doesn't check for long opt style arg values for `--verbose` (I have PR out for this)
* `et --verbose 5` (cxxopts 5, ELPP 9) 
* ELPP doesn't detect the arg for --verbose so sets …
> Explicitly set verbosity from cxxopts value.

- README.md
For systemd, the command must start normally, not as daemon for it to work.
> Remove daemon flag in systemd config

- CMakeLists.txt
- codecov.yml
- src/base/TunnelUtils.cpp
- src/base/TunnelUtils.hpp
- src/terminal/TerminalClient.cpp
- src/terminal/TerminalClientMain.cpp
- test/TerminalTest.cpp
Rather than using STFATAL and exiting, bubble up tunnel parsing exception to main and display the responsible option arg and print help menu so the user need not dig into /tmp/etclient-* to determine why et aborted.
Fixes #491
Testing:
```
❯ ./et -p abc localhost:8080 --macserver                                                                                                                                                                                     14:57:23  12.02.22
Exception: Argument ‘abc’ failed to parse
Remote shell for the busy and impatient
Usage:
et [OPTION...] [user@]host[:port]
Note that 'host' can be a hostname or ipv4 address with or without a port
or an ipv6 address. If the ipv6 address is abbreviated with :: then it must
be specified without a port (use -p,--port). …
```
> Fix tunnel parsing exception handling.

- etc/et.cfg
- src/terminal/TerminalServerMain.cpp
In issue #504, it was brought to attention that while the command line arg for enabling telemetry was boolean, the ini config in et.cfg needed to be an int to change the value.  SimpleIni has a GetBoolValue function that treats the strings "0", "off", "no", "false" as boolean false and "1", "on", "true" as boolean true.
Also, this will make telemetry opt-in as opposed to opt-out as has been requested by multiple users.  The supplied et.cfg file will still have telemetry on.
> Parse telemetry ini config as boolean and make telemetry opt-in.

- README.md
To see which distributions package et.
We could also use a smaller badge like:
https://repology.org/badge/tiny-repos/eternalterminal.svg
What do you prefer?
> Add packaging information

- CMakeLists.txt
The option is enabled by default, so it should not disrupt the default behavior.
> Add BUILD_TESTING to make tests optional by choice

- README.md
- docker/Dockerfile.client
- docker/Dockerfile.server
I got some compile errors when buiding ET on CentOS 7
```
- CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
- A suitable version of git was not found (required v2.7.4) and unable to automatically download a portable one. Please install a newer version of git.
- Can't locate IPC/Cmd.pm
- Can't locate Data/Dumper.pm
- Could NOT find Unwind (missing: Unwind_INCLUDE_DIR Unwind_LIBRARY Unwind_PLATFORM_LIBRARY)
- Could NOT find UTempter (missing: UTEMPTER_INCLUDE_DIR UTEMPTER_LIBRARIES)
- cannot find -latomic
```
Seems docs are too old for building ET on CentOS 7.
So I fix it.
> Fix build on CentOS 7

- download.md
Small typo. "Supported" not "supposed" Debian versions.
> fix typo in download.md

- src/base/TunnelUtils.cpp
- src/terminal/forwarding/PortForwardHandler.cpp
> Force reverse tunnel socket to be binded to localhost

- README.md
Setting this variable actually breaking build on my Macbook with Apple Silicon.
I get this error:
```
Detecting compiler hash for triplet arm64-osx...
error: while detecting compiler information:
The log file content at "/Users/sayfutdinov/Project/github/EternalTerminal/external/vcpkg/buildtrees/detect_compiler/stdout-arm64-osx.log" is:
-- Configuring arm64-osx-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
Command failed: /opt/homebrew/Cellar/cmake/3.27.7/bin/cmake /Users/sayfutdinov/Project/github/EternalTerminal/external/vcpkg/scripts/detect_compiler -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/Users/sayfutdinov/Project/github/EternalTerminal/external/vcpkg/packages/detect_compiler_arm64-osx -DCMAKE_SYSTEM_NAME=Darwin …
```
> Update compiling instructions for Apple Silicon

- README.md
libcurl-dev was moved to libcurl4-openssl-dev
> fix libcurl for ubuntu in README.md

- src/terminal/SshSetupHandler.cpp
- src/terminal/TerminalClientMain.cpp
Don't strip username from `jumphost`, add it if it's missing.
Fix a bug when connecting with two different usernames for server and jumphost.
Fix command line parsing bug when including username in jumphost.
Fix a bug when `ProxyJump` is set in `~/.ssh/config` with a username but without port.
Fix #532
> Don't strip username from `jumphost`, add it if it's missing

- .devcontainer/devcontainer.json
Devcontainer: The original `ubuntu-21.04` image was failing to build, so I switched it to `debian-11` which works out of the box.
Tests: They were failing because `libwinpthread < 10.0` is not available on the `https://repo.msys2.org` anymore. See for example the 404 not found errors [here](https://github.com/MisterTea/EternalTerminal/actions/runs/7741605598/job/21108940236#step:12:165).
So what I did for testing is I updated `vcpkg` one month at the time until the tests started passing and ended up on vcpkg commit [4a3c366](https://github.com/microsoft/vcpkg/commit/4a3c366f2d0d0eaf034bfa649124768df7cfe813).
> Fix devcontainer and update vcpkg for tests

- .github/workflows/clang-format-check.yml
- .github/workflows/codespell.yml
- .github/workflows/linux_ci.yml
- .github/workflows/mac_ci.yml
- .github/workflows/novcpkg_build_master.yml
- .github/workflows/novcpkg_build_release.yml
- .github/workflows/vcpkg_build_master.yml
- .github/workflows/vcpkg_build_release.yml
- docker/Dockerfile.client
- docker/Dockerfile.server
The only non-trivial change is updating `actions/upload-artifact` from `v2` to `v4`, [source](https://github.com/actions/upload-artifact?tab=readme-ov-file#breaking-changes). They don't allow for artifacts with the same name being uploaded and overwriting each other. This happened in the linux-ci workflow where different gcc versions were used but the artifact they produced had the same name, making the `v4` action fail. I fixed it by creating a unique name for each gcc version.
-  name: et-client-${{matrix.os}}
+  name: et-client-${{matrix.os}}-gcc${{matrix.gcc}}
> update actions and docker images

- renovate.json
As discussed in https://github.com/MisterTea/EternalTerminal/pull/622 this pull request adds the [renovatebot](https://docs.renovatebot.com/) to this repo. 
The current config will automatically merge minor updates and patches, major version bumps need to be merged manually.
> add renovatebot

- src/terminal/TerminalServer.cpp
Initial implementation to try and address the high cpu usage discussed in #548.
> increase timeout to address (Relatively) high CPU use #548

- src/terminal/TerminalClientMain.cpp
Caused by https://github.com/MisterTea/EternalTerminal/commit/c1d54e71304fe435eb7bf14bcfa62cf783100314
Should fix https://github.com/MisterTea/EternalTerminal/issues/357#issuecomment-1452357927
> fix: etterminal_path is the incorrect option name

- docs/creating_release.md
- src/terminal/TerminalServerMain.cpp
In addition to opt-in for telemetry (see #553) this uses the log directory override from #556 to place the sentry/telemetry logs.
> Telemetry service directory override.

- README.md
Linux does not use arm64 for uname, so grep does not work, leading in a resulting confusing error.
MacOS (Ventura):
```
Darwin foo 22.6.0 Darwin Kernel Version 22.6.0: Mon Feb 19 19:43:13 PST
2024; root:xnu-8796.141.3.704.6~1/RELEASE_ARM64_T6020 arm64 arm Darwin
```
Linux aarch64 (OrangePi, Ubuntu 22.04):
```
Linux foo 5.10.160-rockchip #37 SMP Fri Apr 26 05:16:30 UTC 2024 aarch64
aarch64 aarch64 GNU/Linux
```
Linux aarch64 (AWS, Ubuntu 24.04):
```
Linux foo 6.8.0-1008-aws #8-Ubuntu SMP Sat Apr 20 02:43:14 UTC 2024
aarch64 aarch64 aarch64 GNU/Linux
```
Tested with both system grep and grep 3.11 installed via Homebrew for MacOS:
```
grep (BSD grep, GNU compatible) 2.6.0-FreeBSD
```
Homebrew:
```
grep (GNU grep) 3.11
Packaged by Homebrew
Copyright (C) 2023 Free Software Foundation, Inc. …
```
> Change grep command in README for arm64 to also work with Linux

- _includes/nav.html
The image link is broken. I changed it to the same one (which seems to be the most official one), and it is the same size. See https://web.archive.org/web/20210107045132/https://eternalterminal.dev/ for a reference.
> [website] Fix the broken GitHub ribbon image

- README.md
This PR speeds up building process by removing unnecessary packages, shrink download size and compile parallely.
I've checked that packages listed in #586 is correct. Removing `libboost-dev` and `libgflags-dev` still build successfully in Ubuntu 24.04.
close #586
> Speedup build process

- docker/Dockerfile.client
- docker/Dockerfile.server
- docker/container-entrypoint
Currently, the Dockerfiles in the offical repo are non-functional, because CentOS is no longer a thing and the official package repository has been taken offline.  As such, this pull request updates them to use Debian 12 and uses the official EternalTerminal repository to install the ET binaries into the container.
> Update Dockerfiles to use a modern distro and the offical package

- src/terminal/TerminalClientMain.cpp
Currently single-value options such as --tunnel will accept multiple values, e.g. --tunnel "<...>" --tunnel "<...>". Confusingly for the user only the last value will be used without any warning.
This commit fixes this by emitting an error message and exiting the program if multiple option values were supplied when single value was expected.
There are several more cases where this same approach could be applied, but these are not as trivial to map to the newly added function (e.g. `result["terminal-path"].as<string>()`), so I left them as is.
> Fix multiple options accepted for single-value options

- src/base/LogHandler.cpp
Fix multi-session log file race on startup
- Fixes https://github.com/MisterTea/EternalTerminal/issues/599
- Starting multiple sessions simultaneously fails with:
```
2024-11-14 08:20:32,278 FATAL [default] Stack Trace:
[0] 0x0000000104486cab et::LogHandler::createLogFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)
[1] 0x000000010448666d et::LogHandler::setupLogFiles(el::Configurations*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, bool, bool, bool, std::__1::basic_string<char, std::__1::char_traits<char>, …
```
> Fix multi-session log file race on startup

- src/terminal/ParseConfigFile.hpp
The SSH config parser avoids parsing everything inside a `Host` block that does not match the host we are trying to connect to.
This makes sense, but the implementation fails on some cases. Consider the following:
`et host.company`
```
Host other.company
User someone
Include ~/.ssh/host.company
```
And inside `~/.ssh/host.company` we have:
```
Host host.company
User gabriel
```
The way the parser works now is:
* Sees the `Host other.company` and sets `parsing = 0` because it does not match the target `host.company`.
* Skips processing the `Include` completely because `parsing = 0`.
* Misses the actual configs defined for `Host host.company`.
This PR simply does not ignore `Include` directives to avoid such cases.
> Fix parsing bug where includes are skipped

- README.md
- systemctl/et.service
This lets the logs from etserver go to the systemd journal, instead of `/tmp`; it's a lot nicer when running under systemd.
> Recommend `--logtostdout` in systemd installations

- src/base/TcpSocketHandler.cpp
- src/terminal/ParseConfigFile.hpp
- src/terminal/TerminalClient.cpp
- src/terminal/TerminalClientMain.cpp
Even though EternalTerminal supports port forwarding by default, it doesn't understand the `LocalForward` directive from ssh config:
>   LocalForward
Specifies that a TCP port on the local machine be
forwarded over the secure channel to the specified host
and port from the remote machine.  The first argument
specifies the listener and may be [bind_address:]port or a
Unix domain socket path.  The second argument is the
destination and may be host:hostport or a Unix domain
socket path if the remote host supports it.
https://man7.org/linux/man-pages/man5/ssh_config.5.html
This is a very crude implementation that simply parses those configs in a straightforward (and incomplete) way and turns all errors into warnings, just like `ssh` does by default.
> Parse LocalForward from SSH config
